image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: saphe solve document.saty

vscode:
  extensions:
    - pickoba.satysfi-workshop
    - james-yu.latex-workshop
